"""
System Cleanup & Disk Space Triage Engine
Analyzes disk usage across Windows drives, calculates reclaimable waste in
temporary folders, Windows Update cache, and crash dumps, and performs safe pruning.
"""

import os
import platform
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional
import psutil

from utils.logger import get_logger

logger = get_logger()


@dataclass
class CleanupCategoryInfo:
    key: str
    name: str
    target_path: str
    description: str
    file_count: int
    total_bytes: int
    total_mb: float
    is_accessible: bool

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class DiskSpaceSummary:
    drive_letter: str
    total_gb: float
    used_gb: float
    free_gb: float
    percent_used: float
    categories: List[CleanupCategoryInfo]
    total_reclaimable_mb: float
    total_reclaimable_gb: float

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CleanupExecutionResult:
    deleted_files: int
    failed_files: int
    freed_bytes: int
    freed_mb: float
    logs: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# =========================================================================
# DIRECTORY PATH DEFINITIONS
# =========================================================================

def get_target_cleanup_directories() -> Dict[str, Dict[str, str]]:
    """Returns standardized paths for reclaimable Windows temporary caches."""
    win_dir = os.environ.get("SystemRoot", "C:\\Windows")
    local_app_data = os.environ.get("LOCALAPPDATA", "")
    program_data = os.environ.get("ProgramData", "C:\\ProgramData")
    user_temp = os.environ.get("TEMP", os.path.join(local_app_data, "Temp"))

    return {
        "user_temp": {
            "name": "User Temporary Files",
            "path": user_temp,
            "desc": "Scratch files, temporary installer extraction caches, and browser temp files."
        },
        "system_temp": {
            "name": "Windows System Temp",
            "path": os.path.join(win_dir, "Temp"),
            "desc": "OS-level background services scratch files and system update logs."
        },
        "win_update_cache": {
            "name": "Windows Update Download Cache",
            "path": os.path.join(win_dir, "SoftwareDistribution", "Download"),
            "desc": "Downloaded update packages (.cab / .msu) that have already been installed."
        },
        "crash_dumps": {
            "name": "Windows Crash Dumps (WER)",
            "path": os.path.join(program_data, "Microsoft", "Windows", "WER", "ReportArchive"),
            "desc": "Memory minidumps (.dmp) created when applications or kernel services crash."
        },
        "user_crash_dumps": {
            "name": "User Application Crash Dumps",
            "path": os.path.join(local_app_data, "CrashDumps"),
            "desc": "User-mode crash reports generated by desktop software."
        },
        "thumbnail_cache": {
            "name": "Windows Thumbnail Cache",
            "path": os.path.join(local_app_data, "Microsoft", "Windows", "Explorer"),
            "desc": "Cached image and video explorer preview thumbnails."
        }
    }


# =========================================================================
# DISK USAGE & WASTE ANALYSIS
# =========================================================================

def get_directory_size(dir_path: str) -> tuple[int, int, bool]:
    """
    Scans directory recursively and calculates (file_count, total_bytes, is_accessible).
    """
    if not os.path.exists(dir_path):
        return 0, 0, False

    file_count = 0
    total_bytes = 0
    accessible = True

    try:
        for root, _, files in os.walk(dir_path):
            for f in files:
                f_path = os.path.join(root, f)
                try:
                    total_bytes += os.path.getsize(f_path)
                    file_count += 1
                except (OSError, PermissionError):
                    continue
    except (OSError, PermissionError):
        accessible = False

    return file_count, total_bytes, accessible


def analyze_disk_space(drive: str = "C:\\") -> DiskSpaceSummary:
    """
    Calculates Drive C: capacity and scans all temporary waste categories.
    """
    # Drive partition stats
    try:
        usage = psutil.disk_usage(drive)
        tot_gb = usage.total / (1024 ** 3)
        usd_gb = usage.used / (1024 ** 3)
        fre_gb = usage.free / (1024 ** 3)
        pct_usd = usage.percent
    except Exception:
        tot_gb, usd_gb, fre_gb, pct_usd = 0.0, 0.0, 0.0, 0.0

    targets = get_target_cleanup_directories()
    categories: List[CleanupCategoryInfo] = []
    total_reclaimable_bytes = 0

    for key, info in targets.items():
        p = info["path"]
        f_count, b_size, access = get_directory_size(p)
        total_reclaimable_bytes += b_size
        mb_size = round(b_size / (1024 ** 2), 2)

        categories.append(CleanupCategoryInfo(
            key=key,
            name=info["name"],
            target_path=p,
            description=info["desc"],
            file_count=f_count,
            total_bytes=b_size,
            total_mb=mb_size,
            is_accessible=access
        ))

    rec_mb = round(total_reclaimable_bytes / (1024 ** 2), 2)
    rec_gb = round(total_reclaimable_bytes / (1024 ** 3), 2)

    logger.info(f"Disk Analysis Complete: {rec_mb} MB reclaimable across {len(categories)} categories.")
    return DiskSpaceSummary(
        drive_letter=drive,
        total_gb=round(tot_gb, 2),
        used_gb=round(usd_gb, 2),
        free_gb=round(fre_gb, 2),
        percent_used=round(pct_usd, 1),
        categories=categories,
        total_reclaimable_mb=rec_mb,
        total_reclaimable_gb=rec_gb
    )


# =========================================================================
# SAFE CLEANUP PRUNING
# =========================================================================

def safe_clean_directory(dir_path: str, delete_subdirs: bool = True) -> tuple[int, int, int, List[str]]:
    """
    Safely deletes files inside a folder without deleting the root folder itself.
    Skips locked files gracefully.
    Returns: (deleted_count, failed_count, freed_bytes, logs)
    """
    if not os.path.exists(dir_path):
        return 0, 0, 0, [f"[*] Path does not exist: {dir_path}"]

    deleted = 0
    failed = 0
    freed_bytes = 0
    logs: List[str] = []

    for item in os.listdir(dir_path):
        item_path = os.path.join(dir_path, item)
        if os.path.isfile(item_path) or os.path.islink(item_path):
            try:
                sz = os.path.getsize(item_path)
                os.remove(item_path)
                freed_bytes += sz
                deleted += 1
            except (PermissionError, OSError):
                failed += 1
        elif os.path.isdir(item_path) and delete_subdirs:
            try:
                # Calculate size before tree removal
                for root, _, files in os.walk(item_path):
                    for f in files:
                        try:
                            freed_bytes += os.path.getsize(os.path.join(root, f))
                            deleted += 1
                        except OSError:
                            pass
                shutil.rmtree(item_path, ignore_errors=False)
            except (PermissionError, OSError):
                failed += 1

    return deleted, failed, freed_bytes, logs


def execute_disk_cleanup(selected_categories: List[str]) -> CleanupExecutionResult:
    """
    Executes safe cleanup across the chosen category keys.
    """
    targets = get_target_cleanup_directories()
    total_deleted = 0
    total_failed = 0
    total_freed_bytes = 0
    all_logs: List[str] = [f"[*] Starting system disk cleanup for {len(selected_categories)} categories..."]

    for cat_key in selected_categories:
        if cat_key not in targets:
            continue
        info = targets[cat_key]
        p = info["path"]
        name = info["name"]

        all_logs.append(f"[*] Pruning '{name}' ({p})...")
        d, f, b, _ = safe_clean_directory(p)
        total_deleted += d
        total_failed += f
        total_freed_bytes += b
        all_logs.append(f"    -> Removed {d} files ({b / (1024**2):.2f} MB freed). Skipped {f} locked files.")

    freed_mb = round(total_freed_bytes / (1024 ** 2), 2)
    all_logs.append(f"[+] Cleanup Complete! Total Freed: {freed_mb} MB ({total_deleted} files removed).")
    logger.info(f"Disk cleanup finished: {freed_mb} MB freed.")

    return CleanupExecutionResult(
        deleted_files=total_deleted,
        failed_files=total_failed,
        freed_bytes=total_freed_bytes,
        freed_mb=freed_mb,
        logs=all_logs
    )
